// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== ENUMS ==========
type DefectStatus int32

const (
	DefectStatus_DEFECT_STATUS_UNSPECIFIED DefectStatus = 0
	DefectStatus_DEFECT_STATUS_NEW         DefectStatus = 1
	DefectStatus_DEFECT_STATUS_IN_WORK     DefectStatus = 2
	DefectStatus_DEFECT_STATUS_IN_REVIEW   DefectStatus = 3
	DefectStatus_DEFECT_STATUS_CLOSED      DefectStatus = 4
	DefectStatus_DEFECT_STATUS_CANCELLED   DefectStatus = 5
)

// Enum value maps for DefectStatus.
var (
	DefectStatus_name = map[int32]string{
		0: "DEFECT_STATUS_UNSPECIFIED",
		1: "DEFECT_STATUS_NEW",
		2: "DEFECT_STATUS_IN_WORK",
		3: "DEFECT_STATUS_IN_REVIEW",
		4: "DEFECT_STATUS_CLOSED",
		5: "DEFECT_STATUS_CANCELLED",
	}
	DefectStatus_value = map[string]int32{
		"DEFECT_STATUS_UNSPECIFIED": 0,
		"DEFECT_STATUS_NEW":         1,
		"DEFECT_STATUS_IN_WORK":     2,
		"DEFECT_STATUS_IN_REVIEW":   3,
		"DEFECT_STATUS_CLOSED":      4,
		"DEFECT_STATUS_CANCELLED":   5,
	}
)

func (x DefectStatus) Enum() *DefectStatus {
	p := new(DefectStatus)
	*p = x
	return p
}

func (x DefectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_project_project_proto_enumTypes[0].Descriptor()
}

func (DefectStatus) Type() protoreflect.EnumType {
	return &file_project_project_proto_enumTypes[0]
}

func (x DefectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefectStatus.Descriptor instead.
func (DefectStatus) EnumDescriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{0}
}

type DefectPriority int32

const (
	DefectPriority_DEFECT_PRIORITY_UNSPECIFIED DefectPriority = 0
	DefectPriority_DEFECT_PRIORITY_LOW         DefectPriority = 1
	DefectPriority_DEFECT_PRIORITY_MEDIUM      DefectPriority = 2
	DefectPriority_DEFECT_PRIORITY_HIGH        DefectPriority = 3
)

// Enum value maps for DefectPriority.
var (
	DefectPriority_name = map[int32]string{
		0: "DEFECT_PRIORITY_UNSPECIFIED",
		1: "DEFECT_PRIORITY_LOW",
		2: "DEFECT_PRIORITY_MEDIUM",
		3: "DEFECT_PRIORITY_HIGH",
	}
	DefectPriority_value = map[string]int32{
		"DEFECT_PRIORITY_UNSPECIFIED": 0,
		"DEFECT_PRIORITY_LOW":         1,
		"DEFECT_PRIORITY_MEDIUM":      2,
		"DEFECT_PRIORITY_HIGH":        3,
	}
)

func (x DefectPriority) Enum() *DefectPriority {
	p := new(DefectPriority)
	*p = x
	return p
}

func (x DefectPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DefectPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_project_project_proto_enumTypes[1].Descriptor()
}

func (DefectPriority) Type() protoreflect.EnumType {
	return &file_project_project_proto_enumTypes[1]
}

func (x DefectPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DefectPriority.Descriptor instead.
func (DefectPriority) EnumDescriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{1}
}

type ProjectStatus int32

const (
	ProjectStatus_PROJECT_STATUS_UNSPECIFIED ProjectStatus = 0
	ProjectStatus_PROJECT_STATUS_ACTIVE      ProjectStatus = 1
	ProjectStatus_PROJECT_STATUS_PLANNING    ProjectStatus = 2
	ProjectStatus_PROJECT_STATUS_COMPLETED   ProjectStatus = 3
	ProjectStatus_PROJECT_STATUS_ARCHIVED    ProjectStatus = 4
)

// Enum value maps for ProjectStatus.
var (
	ProjectStatus_name = map[int32]string{
		0: "PROJECT_STATUS_UNSPECIFIED",
		1: "PROJECT_STATUS_ACTIVE",
		2: "PROJECT_STATUS_PLANNING",
		3: "PROJECT_STATUS_COMPLETED",
		4: "PROJECT_STATUS_ARCHIVED",
	}
	ProjectStatus_value = map[string]int32{
		"PROJECT_STATUS_UNSPECIFIED": 0,
		"PROJECT_STATUS_ACTIVE":      1,
		"PROJECT_STATUS_PLANNING":    2,
		"PROJECT_STATUS_COMPLETED":   3,
		"PROJECT_STATUS_ARCHIVED":    4,
	}
)

func (x ProjectStatus) Enum() *ProjectStatus {
	p := new(ProjectStatus)
	*p = x
	return p
}

func (x ProjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_project_project_proto_enumTypes[2].Descriptor()
}

func (ProjectStatus) Type() protoreflect.EnumType {
	return &file_project_project_proto_enumTypes[2]
}

func (x ProjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectStatus.Descriptor instead.
func (ProjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{2}
}

// ========== ОПЦИОНАЛЬНЫЕ ТИПЫ ==========
type OptionalString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	mi := &file_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OptionalTimestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalTimestamp) Reset() {
	*x = OptionalTimestamp{}
	mi := &file_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalTimestamp) ProtoMessage() {}

func (x *OptionalTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalTimestamp.ProtoReflect.Descriptor instead.
func (*OptionalTimestamp) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *OptionalTimestamp) GetValue() *timestamppb.Timestamp {
	if x != nil {
		return x.Value
	}
	return nil
}

type OptionalProjectStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         ProjectStatus          `protobuf:"varint,1,opt,name=value,proto3,enum=project.ProjectStatus" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalProjectStatus) Reset() {
	*x = OptionalProjectStatus{}
	mi := &file_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalProjectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalProjectStatus) ProtoMessage() {}

func (x *OptionalProjectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalProjectStatus.ProtoReflect.Descriptor instead.
func (*OptionalProjectStatus) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *OptionalProjectStatus) GetValue() ProjectStatus {
	if x != nil {
		return x.Value
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

type OptionalDefectStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         DefectStatus           `protobuf:"varint,1,opt,name=value,proto3,enum=project.DefectStatus" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalDefectStatus) Reset() {
	*x = OptionalDefectStatus{}
	mi := &file_project_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalDefectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalDefectStatus) ProtoMessage() {}

func (x *OptionalDefectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalDefectStatus.ProtoReflect.Descriptor instead.
func (*OptionalDefectStatus) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *OptionalDefectStatus) GetValue() DefectStatus {
	if x != nil {
		return x.Value
	}
	return DefectStatus_DEFECT_STATUS_UNSPECIFIED
}

type OptionalDefectPriority struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         DefectPriority         `protobuf:"varint,1,opt,name=value,proto3,enum=project.DefectPriority" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalDefectPriority) Reset() {
	*x = OptionalDefectPriority{}
	mi := &file_project_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalDefectPriority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalDefectPriority) ProtoMessage() {}

func (x *OptionalDefectPriority) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalDefectPriority.ProtoReflect.Descriptor instead.
func (*OptionalDefectPriority) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *OptionalDefectPriority) GetValue() DefectPriority {
	if x != nil {
		return x.Value
	}
	return DefectPriority_DEFECT_PRIORITY_UNSPECIFIED
}

// ========== МОДЕЛИ ==========
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_project_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{5}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Defect struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status      DefectStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=project.DefectStatus" json:"status,omitempty"`
	Priority    DefectPriority         `protobuf:"varint,5,opt,name=priority,proto3,enum=project.DefectPriority" json:"priority,omitempty"`
	DueDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// ТОЛЬКО ID как в models
	ProjectId     string     `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EngineerId    string     `protobuf:"bytes,10,opt,name=engineer_id,json=engineerId,proto3" json:"engineer_id,omitempty"`
	ReporterId    string     `protobuf:"bytes,11,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Comments      []*Comment `protobuf:"bytes,12,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Defect) Reset() {
	*x = Defect{}
	mi := &file_project_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Defect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Defect) ProtoMessage() {}

func (x *Defect) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Defect.ProtoReflect.Descriptor instead.
func (*Defect) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{6}
}

func (x *Defect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Defect) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Defect) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Defect) GetStatus() DefectStatus {
	if x != nil {
		return x.Status
	}
	return DefectStatus_DEFECT_STATUS_UNSPECIFIED
}

func (x *Defect) GetPriority() DefectPriority {
	if x != nil {
		return x.Priority
	}
	return DefectPriority_DEFECT_PRIORITY_UNSPECIFIED
}

func (x *Defect) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Defect) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Defect) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Defect) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Defect) GetEngineerId() string {
	if x != nil {
		return x.EngineerId
	}
	return ""
}

func (x *Defect) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *Defect) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=project.ProjectStatus" json:"status,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ManagerId     string                 `protobuf:"bytes,7,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	EngineerIds   []string               `protobuf:"bytes,8,rep,name=engineer_ids,json=engineerIds,proto3" json:"engineer_ids,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Defects       []*Defect              `protobuf:"bytes,11,rep,name=defects,proto3" json:"defects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_project_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{7}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *Project) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Project) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Project) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *Project) GetEngineerIds() []string {
	if x != nil {
		return x.EngineerIds
	}
	return nil
}

func (x *Project) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Project) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Project) GetDefects() []*Defect {
	if x != nil {
		return x.Defects
	}
	return nil
}

// ========== ФИЛЬТРЫ ==========
type DefectFilter struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ProjectId     *OptionalString         `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EngineerId    *OptionalString         `protobuf:"bytes,2,opt,name=engineer_id,json=engineerId,proto3" json:"engineer_id,omitempty"`
	ReporterId    *OptionalString         `protobuf:"bytes,3,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Status        *OptionalDefectStatus   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority      *OptionalDefectPriority `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Search        *OptionalString         `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefectFilter) Reset() {
	*x = DefectFilter{}
	mi := &file_project_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefectFilter) ProtoMessage() {}

func (x *DefectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefectFilter.ProtoReflect.Descriptor instead.
func (*DefectFilter) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{8}
}

func (x *DefectFilter) GetProjectId() *OptionalString {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *DefectFilter) GetEngineerId() *OptionalString {
	if x != nil {
		return x.EngineerId
	}
	return nil
}

func (x *DefectFilter) GetReporterId() *OptionalString {
	if x != nil {
		return x.ReporterId
	}
	return nil
}

func (x *DefectFilter) GetStatus() *OptionalDefectStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DefectFilter) GetPriority() *OptionalDefectPriority {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *DefectFilter) GetSearch() *OptionalString {
	if x != nil {
		return x.Search
	}
	return nil
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_project_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{9}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PaginationRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type PaginatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedResponse) Reset() {
	*x = PaginatedResponse{}
	mi := &file_project_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedResponse) ProtoMessage() {}

func (x *PaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedResponse.ProtoReflect.Descriptor instead.
func (*PaginatedResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{10}
}

func (x *PaginatedResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginatedResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatedResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginatedResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// ========== ЗАПРОСЫ ==========
type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	EngineerIds   []string               `protobuf:"bytes,4,rep,name=engineer_ids,json=engineerIds,proto3" json:"engineer_ids,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_project_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{11}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CreateProjectRequest) GetEngineerIds() []string {
	if x != nil {
		return x.EngineerIds
	}
	return nil
}

func (x *CreateProjectRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateProjectRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_project_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{12}
}

func (x *GetProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	Status        ProjectStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=project.ProjectStatus" json:"status,omitempty"`
	EngineerId    string                 `protobuf:"bytes,3,opt,name=engineer_id,json=engineerId,proto3" json:"engineer_id,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_project_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{13}
}

func (x *ListProjectsRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *ListProjectsRequest) GetStatus() ProjectStatus {
	if x != nil {
		return x.Status
	}
	return ProjectStatus_PROJECT_STATUS_UNSPECIFIED
}

func (x *ListProjectsRequest) GetEngineerId() string {
	if x != nil {
		return x.EngineerId
	}
	return ""
}

func (x *ListProjectsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListProjectsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_project_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{14}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProjectsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProjectsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          *OptionalString        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *OptionalString        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        *OptionalProjectStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartDate     *OptionalTimestamp     `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *OptionalTimestamp     `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProjectRequest) Reset() {
	*x = UpdateProjectRequest{}
	mi := &file_project_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProjectRequest) ProtoMessage() {}

func (x *UpdateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProjectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateProjectRequest) GetName() *OptionalString {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateProjectRequest) GetDescription() *OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateProjectRequest) GetStatus() *OptionalProjectStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateProjectRequest) GetStartDate() *OptionalTimestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateProjectRequest) GetEndDate() *OptionalTimestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type AddEngineersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EngineerIds   []string               `protobuf:"bytes,2,rep,name=engineer_ids,json=engineerIds,proto3" json:"engineer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEngineersRequest) Reset() {
	*x = AddEngineersRequest{}
	mi := &file_project_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEngineersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEngineersRequest) ProtoMessage() {}

func (x *AddEngineersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEngineersRequest.ProtoReflect.Descriptor instead.
func (*AddEngineersRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{16}
}

func (x *AddEngineersRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AddEngineersRequest) GetEngineerIds() []string {
	if x != nil {
		return x.EngineerIds
	}
	return nil
}

type RemoveEngineerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EngineerId    string                 `protobuf:"bytes,2,opt,name=engineer_id,json=engineerId,proto3" json:"engineer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEngineerRequest) Reset() {
	*x = RemoveEngineerRequest{}
	mi := &file_project_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEngineerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEngineerRequest) ProtoMessage() {}

func (x *RemoveEngineerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEngineerRequest.ProtoReflect.Descriptor instead.
func (*RemoveEngineerRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveEngineerRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RemoveEngineerRequest) GetEngineerId() string {
	if x != nil {
		return x.EngineerId
	}
	return ""
}

type ValidateAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessRequest) Reset() {
	*x = ValidateAccessRequest{}
	mi := &file_project_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessRequest) ProtoMessage() {}

func (x *ValidateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateAccessRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ValidateAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ValidateAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	RoleInProject string                 `protobuf:"bytes,2,opt,name=role_in_project,json=roleInProject,proto3" json:"role_in_project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessResponse) Reset() {
	*x = ValidateAccessResponse{}
	mi := &file_project_project_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessResponse) ProtoMessage() {}

func (x *ValidateAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{19}
}

func (x *ValidateAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *ValidateAccessResponse) GetRoleInProject() string {
	if x != nil {
		return x.RoleInProject
	}
	return ""
}

type CreateDefectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      DefectPriority         `protobuf:"varint,3,opt,name=priority,proto3,enum=project.DefectPriority" json:"priority,omitempty"`
	ProjectId     string                 `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EngineerId    string                 `protobuf:"bytes,5,opt,name=engineer_id,json=engineerId,proto3" json:"engineer_id,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDefectRequest) Reset() {
	*x = CreateDefectRequest{}
	mi := &file_project_project_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDefectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDefectRequest) ProtoMessage() {}

func (x *CreateDefectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDefectRequest.ProtoReflect.Descriptor instead.
func (*CreateDefectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{20}
}

func (x *CreateDefectRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDefectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDefectRequest) GetPriority() DefectPriority {
	if x != nil {
		return x.Priority
	}
	return DefectPriority_DEFECT_PRIORITY_UNSPECIFIED
}

func (x *CreateDefectRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateDefectRequest) GetEngineerId() string {
	if x != nil {
		return x.EngineerId
	}
	return ""
}

func (x *CreateDefectRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

type GetDefectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefectRequest) Reset() {
	*x = GetDefectRequest{}
	mi := &file_project_project_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefectRequest) ProtoMessage() {}

func (x *GetDefectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefectRequest.ProtoReflect.Descriptor instead.
func (*GetDefectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{21}
}

func (x *GetDefectRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

type ListDefectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *DefectFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *PaginationRequest     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefectsRequest) Reset() {
	*x = ListDefectsRequest{}
	mi := &file_project_project_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefectsRequest) ProtoMessage() {}

func (x *ListDefectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefectsRequest.ProtoReflect.Descriptor instead.
func (*ListDefectsRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{22}
}

func (x *ListDefectsRequest) GetFilter() *DefectFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListDefectsRequest) GetPagination() *PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListDefectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Defects       []*Defect              `protobuf:"bytes,1,rep,name=defects,proto3" json:"defects,omitempty"`
	Pagination    *PaginatedResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefectsResponse) Reset() {
	*x = ListDefectsResponse{}
	mi := &file_project_project_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefectsResponse) ProtoMessage() {}

func (x *ListDefectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefectsResponse.ProtoReflect.Descriptor instead.
func (*ListDefectsResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{23}
}

func (x *ListDefectsResponse) GetDefects() []*Defect {
	if x != nil {
		return x.Defects
	}
	return nil
}

func (x *ListDefectsResponse) GetPagination() *PaginatedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateDefectStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	Status        DefectStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=project.DefectStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefectStatusRequest) Reset() {
	*x = UpdateDefectStatusRequest{}
	mi := &file_project_project_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefectStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefectStatusRequest) ProtoMessage() {}

func (x *UpdateDefectStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefectStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefectStatusRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateDefectStatusRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *UpdateDefectStatusRequest) GetStatus() DefectStatus {
	if x != nil {
		return x.Status
	}
	return DefectStatus_DEFECT_STATUS_UNSPECIFIED
}

type UpdateDefectPriorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	Priority      DefectPriority         `protobuf:"varint,2,opt,name=priority,proto3,enum=project.DefectPriority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefectPriorityRequest) Reset() {
	*x = UpdateDefectPriorityRequest{}
	mi := &file_project_project_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefectPriorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefectPriorityRequest) ProtoMessage() {}

func (x *UpdateDefectPriorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefectPriorityRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefectPriorityRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateDefectPriorityRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *UpdateDefectPriorityRequest) GetPriority() DefectPriority {
	if x != nil {
		return x.Priority
	}
	return DefectPriority_DEFECT_PRIORITY_UNSPECIFIED
}

type AssignEngineerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	EngineerId    string                 `protobuf:"bytes,2,opt,name=engineer_id,json=engineerId,proto3" json:"engineer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignEngineerRequest) Reset() {
	*x = AssignEngineerRequest{}
	mi := &file_project_project_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignEngineerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignEngineerRequest) ProtoMessage() {}

func (x *AssignEngineerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignEngineerRequest.ProtoReflect.Descriptor instead.
func (*AssignEngineerRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{26}
}

func (x *AssignEngineerRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *AssignEngineerRequest) GetEngineerId() string {
	if x != nil {
		return x.EngineerId
	}
	return ""
}

type UpdateDefectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	Title         *OptionalString        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *OptionalString        `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *OptionalTimestamp     `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefectRequest) Reset() {
	*x = UpdateDefectRequest{}
	mi := &file_project_project_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefectRequest) ProtoMessage() {}

func (x *UpdateDefectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefectRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefectRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateDefectRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *UpdateDefectRequest) GetTitle() *OptionalString {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdateDefectRequest) GetDescription() *OptionalString {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateDefectRequest) GetDueDate() *OptionalTimestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

type AddCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_project_project_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{28}
}

func (x *AddCommentRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *AddCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AddCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_project_project_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_project_project_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefectId      string                 `protobuf:"bytes,1,opt,name=defect_id,json=defectId,proto3" json:"defect_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_project_project_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{31}
}

func (x *GetCommentsRequest) GetDefectId() string {
	if x != nil {
		return x.DefectId
	}
	return ""
}

func (x *GetCommentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_project_project_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{32}
}

func (x *GetCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCommentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_project_project_proto protoreflect.FileDescriptor

const file_project_project_proto_rawDesc = "" +
	"\n" +
	"\x15project/project.proto\x12\aproject\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\x0eOptionalString\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"E\n" +
	"\x11OptionalTimestamp\x120\n" +
	"\x05value\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05value\"E\n" +
	"\x15OptionalProjectStatus\x12,\n" +
	"\x05value\x18\x01 \x01(\x0e2\x16.project.ProjectStatusR\x05value\"C\n" +
	"\x14OptionalDefectStatus\x12+\n" +
	"\x05value\x18\x01 \x01(\x0e2\x15.project.DefectStatusR\x05value\"G\n" +
	"\x16OptionalDefectPriority\x12-\n" +
	"\x05value\x18\x01 \x01(\x0e2\x17.project.DefectPriorityR\x05value\"\xbc\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf0\x03\n" +
	"\x06Defect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.project.DefectStatusR\x06status\x123\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x17.project.DefectPriorityR\bpriority\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\x12\x1f\n" +
	"\vengineer_id\x18\n" +
	" \x01(\tR\n" +
	"engineerId\x12\x1f\n" +
	"\vreporter_id\x18\v \x01(\tR\n" +
	"reporterId\x12,\n" +
	"\bcomments\x18\f \x03(\v2\x10.project.CommentR\bcomments\"\xd4\x03\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.project.ProjectStatusR\x06status\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1d\n" +
	"\n" +
	"manager_id\x18\a \x01(\tR\tmanagerId\x12!\n" +
	"\fengineer_ids\x18\b \x03(\tR\vengineerIds\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\adefects\x18\v \x03(\v2\x0f.project.DefectR\adefects\"\xdf\x02\n" +
	"\fDefectFilter\x126\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v2\x17.project.OptionalStringR\tprojectId\x128\n" +
	"\vengineer_id\x18\x02 \x01(\v2\x17.project.OptionalStringR\n" +
	"engineerId\x128\n" +
	"\vreporter_id\x18\x03 \x01(\v2\x17.project.OptionalStringR\n" +
	"reporterId\x125\n" +
	"\x06status\x18\x04 \x01(\v2\x1d.project.OptionalDefectStatusR\x06status\x12;\n" +
	"\bpriority\x18\x05 \x01(\v2\x1f.project.OptionalDefectPriorityR\bpriority\x12/\n" +
	"\x06search\x18\x06 \x01(\v2\x17.project.OptionalStringR\x06search\"u\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"t\n" +
	"\x11PaginatedResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\x80\x02\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\x12!\n" +
	"\fengineer_ids\x18\x04 \x03(\tR\vengineerIds\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"2\n" +
	"\x11GetProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"\xc7\x01\n" +
	"\x13ListProjectsRequest\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\tR\tmanagerId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.project.ProjectStatusR\x06status\x12\x1f\n" +
	"\vengineer_id\x18\x03 \x01(\tR\n" +
	"engineerId\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\x84\x01\n" +
	"\x14ListProjectsResponse\x12,\n" +
	"\bprojects\x18\x01 \x03(\v2\x10.project.ProjectR\bprojects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc7\x02\n" +
	"\x14UpdateProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12+\n" +
	"\x04name\x18\x02 \x01(\v2\x17.project.OptionalStringR\x04name\x129\n" +
	"\vdescription\x18\x03 \x01(\v2\x17.project.OptionalStringR\vdescription\x126\n" +
	"\x06status\x18\x04 \x01(\v2\x1e.project.OptionalProjectStatusR\x06status\x129\n" +
	"\n" +
	"start_date\x18\x05 \x01(\v2\x1a.project.OptionalTimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x06 \x01(\v2\x1a.project.OptionalTimestampR\aendDate\"W\n" +
	"\x13AddEngineersRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12!\n" +
	"\fengineer_ids\x18\x02 \x03(\tR\vengineerIds\"W\n" +
	"\x15RemoveEngineerRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vengineer_id\x18\x02 \x01(\tR\n" +
	"engineerId\"O\n" +
	"\x15ValidateAccessRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"_\n" +
	"\x16ValidateAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12&\n" +
	"\x0frole_in_project\x18\x02 \x01(\tR\rroleInProject\"\xf9\x01\n" +
	"\x13CreateDefectRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x123\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x17.project.DefectPriorityR\bpriority\x12\x1d\n" +
	"\n" +
	"project_id\x18\x04 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vengineer_id\x18\x05 \x01(\tR\n" +
	"engineerId\x125\n" +
	"\bdue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"/\n" +
	"\x10GetDefectRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\"\x7f\n" +
	"\x12ListDefectsRequest\x12-\n" +
	"\x06filter\x18\x01 \x01(\v2\x15.project.DefectFilterR\x06filter\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.project.PaginationRequestR\n" +
	"pagination\"|\n" +
	"\x13ListDefectsResponse\x12)\n" +
	"\adefects\x18\x01 \x03(\v2\x0f.project.DefectR\adefects\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.project.PaginatedResponseR\n" +
	"pagination\"g\n" +
	"\x19UpdateDefectStatusRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.project.DefectStatusR\x06status\"o\n" +
	"\x1bUpdateDefectPriorityRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x123\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x17.project.DefectPriorityR\bpriority\"U\n" +
	"\x15AssignEngineerRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12\x1f\n" +
	"\vengineer_id\x18\x02 \x01(\tR\n" +
	"engineerId\"\xd3\x01\n" +
	"\x13UpdateDefectRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12-\n" +
	"\x05title\x18\x02 \x01(\v2\x17.project.OptionalStringR\x05title\x129\n" +
	"\vdescription\x18\x03 \x01(\v2\x17.project.OptionalStringR\vdescription\x125\n" +
	"\bdue_date\x18\x04 \x01(\v2\x1a.project.OptionalTimestampR\adueDate\"]\n" +
	"\x11AddCommentRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"I\n" +
	"\x14UpdateCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"[\n" +
	"\x12GetCommentsRequest\x12\x1b\n" +
	"\tdefect_id\x18\x01 \x01(\tR\bdefectId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x13GetCommentsResponse\x12,\n" +
	"\bcomments\x18\x01 \x03(\v2\x10.project.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit*\xb3\x01\n" +
	"\fDefectStatus\x12\x1d\n" +
	"\x19DEFECT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DEFECT_STATUS_NEW\x10\x01\x12\x19\n" +
	"\x15DEFECT_STATUS_IN_WORK\x10\x02\x12\x1b\n" +
	"\x17DEFECT_STATUS_IN_REVIEW\x10\x03\x12\x18\n" +
	"\x14DEFECT_STATUS_CLOSED\x10\x04\x12\x1b\n" +
	"\x17DEFECT_STATUS_CANCELLED\x10\x05*\x80\x01\n" +
	"\x0eDefectPriority\x12\x1f\n" +
	"\x1bDEFECT_PRIORITY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEFECT_PRIORITY_LOW\x10\x01\x12\x1a\n" +
	"\x16DEFECT_PRIORITY_MEDIUM\x10\x02\x12\x18\n" +
	"\x14DEFECT_PRIORITY_HIGH\x10\x03*\xa2\x01\n" +
	"\rProjectStatus\x12\x1e\n" +
	"\x1aPROJECT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROJECT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17PROJECT_STATUS_PLANNING\x10\x02\x12\x1c\n" +
	"\x18PROJECT_STATUS_COMPLETED\x10\x03\x12\x1b\n" +
	"\x17PROJECT_STATUS_ARCHIVED\x10\x042\xea\n" +
	"\n" +
	"\x0eProjectService\x12@\n" +
	"\rCreateProject\x12\x1d.project.CreateProjectRequest\x1a\x10.project.Project\x12:\n" +
	"\n" +
	"GetProject\x12\x1a.project.GetProjectRequest\x1a\x10.project.Project\x12K\n" +
	"\fListProjects\x12\x1c.project.ListProjectsRequest\x1a\x1d.project.ListProjectsResponse\x12@\n" +
	"\rUpdateProject\x12\x1d.project.UpdateProjectRequest\x1a\x10.project.Project\x12C\n" +
	"\rDeleteProject\x12\x1a.project.GetProjectRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fAddEngineers\x12\x1c.project.AddEngineersRequest\x1a\x10.project.Project\x12B\n" +
	"\x0eRemoveEngineer\x12\x1e.project.RemoveEngineerRequest\x1a\x10.project.Project\x12Q\n" +
	"\x0eValidateAccess\x12\x1e.project.ValidateAccessRequest\x1a\x1f.project.ValidateAccessResponse\x12=\n" +
	"\fCreateDefect\x12\x1c.project.CreateDefectRequest\x1a\x0f.project.Defect\x127\n" +
	"\tGetDefect\x12\x19.project.GetDefectRequest\x1a\x0f.project.Defect\x12H\n" +
	"\vListDefects\x12\x1b.project.ListDefectsRequest\x1a\x1c.project.ListDefectsResponse\x12=\n" +
	"\fUpdateDefect\x12\x1c.project.UpdateDefectRequest\x1a\x0f.project.Defect\x12I\n" +
	"\x12UpdateDefectStatus\x12\".project.UpdateDefectStatusRequest\x1a\x0f.project.Defect\x12M\n" +
	"\x14UpdateDefectPriority\x12$.project.UpdateDefectPriorityRequest\x1a\x0f.project.Defect\x12A\n" +
	"\x0eAssignEngineer\x12\x1e.project.AssignEngineerRequest\x1a\x0f.project.Defect\x12A\n" +
	"\fDeleteDefect\x12\x19.project.GetDefectRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\n" +
	"AddComment\x12\x1a.project.AddCommentRequest\x1a\x10.project.Comment\x12@\n" +
	"\rUpdateComment\x12\x1d.project.UpdateCommentRequest\x1a\x10.project.Comment\x12F\n" +
	"\rDeleteComment\x12\x1d.project.DeleteCommentRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\vGetComments\x12\x1b.project.GetCommentsRequest\x1a\x1c.project.GetCommentsResponseB'Z%awesome-defect-tracker/shared/projectb\x06proto3"

var (
	file_project_project_proto_rawDescOnce sync.Once
	file_project_project_proto_rawDescData []byte
)

func file_project_project_proto_rawDescGZIP() []byte {
	file_project_project_proto_rawDescOnce.Do(func() {
		file_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)))
	})
	return file_project_project_proto_rawDescData
}

var file_project_project_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_project_project_proto_goTypes = []any{
	(DefectStatus)(0),                   // 0: project.DefectStatus
	(DefectPriority)(0),                 // 1: project.DefectPriority
	(ProjectStatus)(0),                  // 2: project.ProjectStatus
	(*OptionalString)(nil),              // 3: project.OptionalString
	(*OptionalTimestamp)(nil),           // 4: project.OptionalTimestamp
	(*OptionalProjectStatus)(nil),       // 5: project.OptionalProjectStatus
	(*OptionalDefectStatus)(nil),        // 6: project.OptionalDefectStatus
	(*OptionalDefectPriority)(nil),      // 7: project.OptionalDefectPriority
	(*Comment)(nil),                     // 8: project.Comment
	(*Defect)(nil),                      // 9: project.Defect
	(*Project)(nil),                     // 10: project.Project
	(*DefectFilter)(nil),                // 11: project.DefectFilter
	(*PaginationRequest)(nil),           // 12: project.PaginationRequest
	(*PaginatedResponse)(nil),           // 13: project.PaginatedResponse
	(*CreateProjectRequest)(nil),        // 14: project.CreateProjectRequest
	(*GetProjectRequest)(nil),           // 15: project.GetProjectRequest
	(*ListProjectsRequest)(nil),         // 16: project.ListProjectsRequest
	(*ListProjectsResponse)(nil),        // 17: project.ListProjectsResponse
	(*UpdateProjectRequest)(nil),        // 18: project.UpdateProjectRequest
	(*AddEngineersRequest)(nil),         // 19: project.AddEngineersRequest
	(*RemoveEngineerRequest)(nil),       // 20: project.RemoveEngineerRequest
	(*ValidateAccessRequest)(nil),       // 21: project.ValidateAccessRequest
	(*ValidateAccessResponse)(nil),      // 22: project.ValidateAccessResponse
	(*CreateDefectRequest)(nil),         // 23: project.CreateDefectRequest
	(*GetDefectRequest)(nil),            // 24: project.GetDefectRequest
	(*ListDefectsRequest)(nil),          // 25: project.ListDefectsRequest
	(*ListDefectsResponse)(nil),         // 26: project.ListDefectsResponse
	(*UpdateDefectStatusRequest)(nil),   // 27: project.UpdateDefectStatusRequest
	(*UpdateDefectPriorityRequest)(nil), // 28: project.UpdateDefectPriorityRequest
	(*AssignEngineerRequest)(nil),       // 29: project.AssignEngineerRequest
	(*UpdateDefectRequest)(nil),         // 30: project.UpdateDefectRequest
	(*AddCommentRequest)(nil),           // 31: project.AddCommentRequest
	(*UpdateCommentRequest)(nil),        // 32: project.UpdateCommentRequest
	(*DeleteCommentRequest)(nil),        // 33: project.DeleteCommentRequest
	(*GetCommentsRequest)(nil),          // 34: project.GetCommentsRequest
	(*GetCommentsResponse)(nil),         // 35: project.GetCommentsResponse
	(*timestamppb.Timestamp)(nil),       // 36: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 37: google.protobuf.Empty
}
var file_project_project_proto_depIdxs = []int32{
	36, // 0: project.OptionalTimestamp.value:type_name -> google.protobuf.Timestamp
	2,  // 1: project.OptionalProjectStatus.value:type_name -> project.ProjectStatus
	0,  // 2: project.OptionalDefectStatus.value:type_name -> project.DefectStatus
	1,  // 3: project.OptionalDefectPriority.value:type_name -> project.DefectPriority
	36, // 4: project.Comment.created_at:type_name -> google.protobuf.Timestamp
	36, // 5: project.Comment.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 6: project.Defect.status:type_name -> project.DefectStatus
	1,  // 7: project.Defect.priority:type_name -> project.DefectPriority
	36, // 8: project.Defect.due_date:type_name -> google.protobuf.Timestamp
	36, // 9: project.Defect.created_at:type_name -> google.protobuf.Timestamp
	36, // 10: project.Defect.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 11: project.Defect.comments:type_name -> project.Comment
	2,  // 12: project.Project.status:type_name -> project.ProjectStatus
	36, // 13: project.Project.start_date:type_name -> google.protobuf.Timestamp
	36, // 14: project.Project.end_date:type_name -> google.protobuf.Timestamp
	36, // 15: project.Project.created_at:type_name -> google.protobuf.Timestamp
	36, // 16: project.Project.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 17: project.Project.defects:type_name -> project.Defect
	3,  // 18: project.DefectFilter.project_id:type_name -> project.OptionalString
	3,  // 19: project.DefectFilter.engineer_id:type_name -> project.OptionalString
	3,  // 20: project.DefectFilter.reporter_id:type_name -> project.OptionalString
	6,  // 21: project.DefectFilter.status:type_name -> project.OptionalDefectStatus
	7,  // 22: project.DefectFilter.priority:type_name -> project.OptionalDefectPriority
	3,  // 23: project.DefectFilter.search:type_name -> project.OptionalString
	36, // 24: project.CreateProjectRequest.start_date:type_name -> google.protobuf.Timestamp
	36, // 25: project.CreateProjectRequest.end_date:type_name -> google.protobuf.Timestamp
	2,  // 26: project.ListProjectsRequest.status:type_name -> project.ProjectStatus
	10, // 27: project.ListProjectsResponse.projects:type_name -> project.Project
	3,  // 28: project.UpdateProjectRequest.name:type_name -> project.OptionalString
	3,  // 29: project.UpdateProjectRequest.description:type_name -> project.OptionalString
	5,  // 30: project.UpdateProjectRequest.status:type_name -> project.OptionalProjectStatus
	4,  // 31: project.UpdateProjectRequest.start_date:type_name -> project.OptionalTimestamp
	4,  // 32: project.UpdateProjectRequest.end_date:type_name -> project.OptionalTimestamp
	1,  // 33: project.CreateDefectRequest.priority:type_name -> project.DefectPriority
	36, // 34: project.CreateDefectRequest.due_date:type_name -> google.protobuf.Timestamp
	11, // 35: project.ListDefectsRequest.filter:type_name -> project.DefectFilter
	12, // 36: project.ListDefectsRequest.pagination:type_name -> project.PaginationRequest
	9,  // 37: project.ListDefectsResponse.defects:type_name -> project.Defect
	13, // 38: project.ListDefectsResponse.pagination:type_name -> project.PaginatedResponse
	0,  // 39: project.UpdateDefectStatusRequest.status:type_name -> project.DefectStatus
	1,  // 40: project.UpdateDefectPriorityRequest.priority:type_name -> project.DefectPriority
	3,  // 41: project.UpdateDefectRequest.title:type_name -> project.OptionalString
	3,  // 42: project.UpdateDefectRequest.description:type_name -> project.OptionalString
	4,  // 43: project.UpdateDefectRequest.due_date:type_name -> project.OptionalTimestamp
	8,  // 44: project.GetCommentsResponse.comments:type_name -> project.Comment
	14, // 45: project.ProjectService.CreateProject:input_type -> project.CreateProjectRequest
	15, // 46: project.ProjectService.GetProject:input_type -> project.GetProjectRequest
	16, // 47: project.ProjectService.ListProjects:input_type -> project.ListProjectsRequest
	18, // 48: project.ProjectService.UpdateProject:input_type -> project.UpdateProjectRequest
	15, // 49: project.ProjectService.DeleteProject:input_type -> project.GetProjectRequest
	19, // 50: project.ProjectService.AddEngineers:input_type -> project.AddEngineersRequest
	20, // 51: project.ProjectService.RemoveEngineer:input_type -> project.RemoveEngineerRequest
	21, // 52: project.ProjectService.ValidateAccess:input_type -> project.ValidateAccessRequest
	23, // 53: project.ProjectService.CreateDefect:input_type -> project.CreateDefectRequest
	24, // 54: project.ProjectService.GetDefect:input_type -> project.GetDefectRequest
	25, // 55: project.ProjectService.ListDefects:input_type -> project.ListDefectsRequest
	30, // 56: project.ProjectService.UpdateDefect:input_type -> project.UpdateDefectRequest
	27, // 57: project.ProjectService.UpdateDefectStatus:input_type -> project.UpdateDefectStatusRequest
	28, // 58: project.ProjectService.UpdateDefectPriority:input_type -> project.UpdateDefectPriorityRequest
	29, // 59: project.ProjectService.AssignEngineer:input_type -> project.AssignEngineerRequest
	24, // 60: project.ProjectService.DeleteDefect:input_type -> project.GetDefectRequest
	31, // 61: project.ProjectService.AddComment:input_type -> project.AddCommentRequest
	32, // 62: project.ProjectService.UpdateComment:input_type -> project.UpdateCommentRequest
	33, // 63: project.ProjectService.DeleteComment:input_type -> project.DeleteCommentRequest
	34, // 64: project.ProjectService.GetComments:input_type -> project.GetCommentsRequest
	10, // 65: project.ProjectService.CreateProject:output_type -> project.Project
	10, // 66: project.ProjectService.GetProject:output_type -> project.Project
	17, // 67: project.ProjectService.ListProjects:output_type -> project.ListProjectsResponse
	10, // 68: project.ProjectService.UpdateProject:output_type -> project.Project
	37, // 69: project.ProjectService.DeleteProject:output_type -> google.protobuf.Empty
	10, // 70: project.ProjectService.AddEngineers:output_type -> project.Project
	10, // 71: project.ProjectService.RemoveEngineer:output_type -> project.Project
	22, // 72: project.ProjectService.ValidateAccess:output_type -> project.ValidateAccessResponse
	9,  // 73: project.ProjectService.CreateDefect:output_type -> project.Defect
	9,  // 74: project.ProjectService.GetDefect:output_type -> project.Defect
	26, // 75: project.ProjectService.ListDefects:output_type -> project.ListDefectsResponse
	9,  // 76: project.ProjectService.UpdateDefect:output_type -> project.Defect
	9,  // 77: project.ProjectService.UpdateDefectStatus:output_type -> project.Defect
	9,  // 78: project.ProjectService.UpdateDefectPriority:output_type -> project.Defect
	9,  // 79: project.ProjectService.AssignEngineer:output_type -> project.Defect
	37, // 80: project.ProjectService.DeleteDefect:output_type -> google.protobuf.Empty
	8,  // 81: project.ProjectService.AddComment:output_type -> project.Comment
	8,  // 82: project.ProjectService.UpdateComment:output_type -> project.Comment
	37, // 83: project.ProjectService.DeleteComment:output_type -> google.protobuf.Empty
	35, // 84: project.ProjectService.GetComments:output_type -> project.GetCommentsResponse
	65, // [65:85] is the sub-list for method output_type
	45, // [45:65] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_project_project_proto_init() }
func file_project_project_proto_init() {
	if File_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_project_proto_goTypes,
		DependencyIndexes: file_project_project_proto_depIdxs,
		EnumInfos:         file_project_project_proto_enumTypes,
		MessageInfos:      file_project_project_proto_msgTypes,
	}.Build()
	File_project_project_proto = out.File
	file_project_project_proto_goTypes = nil
	file_project_project_proto_depIdxs = nil
}
